apiVersion: "stable.agones.dev/v1alpha1"
kind: GameServerSet
metadata:
  name: simple-udp
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7654
      template:
        spec:
          containers:
            - name: simple-udp
              image: gcr.io/agones-images/udp-server:0.7